---
chartName: openshift-mta
chartVersion: 1.0.0
chartSources:
- https://github.com/jkroepke/openshift-mta

chartMaintainers:
- name: Jan-Otto Kröpke

chartDependencies:
- name: postgresql
  version: 0.9.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: redis
  version: 3.2.5
  repository: https://kubernetes-charts.storage.googleapis.com

applications:
  mailout:
    kind: deployment
    image: a
    ports:
      SMTP:
        port: 25
        protocol: TCP
    pvc: {}
